print("########################\n")
print("#                      #\n")
print("# OKTAVIA LAILA QODARI #\n")
print("#    2410817120013     #\n")
print("#                      #\n")
print("########################\n")
